repos:
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        language_version: python3.9
        args: [--all-files]

-   repo: https://github.com/asottile/blacken-docs
    rev: 1.15.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==22.12.0]
        args: [--all-files]

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black",--all-files]