version: "3"

services:
  web:
    build: 
      context: .
      dockerfile: ./dockerfiles/fastapi/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - wallets-db
    networks:
      - indy_demo
    env_file: 
      - resources/fastapi.default.env
  wallets-db:
    image: postgres:11
    container_name: wallets-db
    command: postgres -c listen_addresses='*'
    env_file: 
      - resources/db.default.env
    volumes:
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - indy_demo
    tty: true
  ngrok-multitenant:
    image: wernight/ngrok
    env_file:
      - resources/aca-py-agent.default.env
    command: ngrok http multitenant-agent:3020 --log stdout
    networks:
      - indy_demo
  multitenant-agent:
    build:
      context: .
      dockerfile: dockerfiles/agents/Dockerfile.agent
    env_file:
      - resources/aca-py-agent.default.env
    ports:
      - 3020:3020
      - 3021:3021
    depends_on:
      - wallets-db
    networks:
      - indy_demo

networks:
  indy_demo:
