version: "3"

services:
  web:
    build: 
      context: .
      dockerfile: ./dockerfiles/fastapi/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - wallets-db
    networks:
      - indy_demo
  wallets-db:
    image: postgres:11
    container_name: wallets-db
    command: postgres -c listen_addresses='*'
    env_file: 
      - resources/db.default.env
    volumes:
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - indy_demo
    tty: true
  ngrok-multitenant:
    image: wernight/ngrok
    env_file: 
      - resources/aca-py-agent.default.env
    command: ngrok http multitenant-agent:${MULTITENANT_HTTP_PORT} --log stdout
    networks:
      - indy_demo
  multitenant-agent:
    build:
      context: ../
      dockerfile: ./dockerfiles/agents/Dockerfile.ngrok
    env_file: 
      - resources/aca-py-agent.default.env
    ports:
      - 8020:7021
      - 8021:7021
    depends_on:
      - wallets-db
    networks:
      - indy_demo

networks:
  indy_demo:
