version: "3"

services:
  web:
    build: 
      context: ../
      dockerfile: ./dockerfiles/fastapi/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - wallets-db
    networks:
      - indy_demo
  wallets-db:
    image: postgres:11
    container_name: wallets-db
    command: postgres -c listen_addresses='*'
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_USER: postgres
      POSTGRES_DB: wallets
    volumes:
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - indy_demo
    tty: true
  # ngrok-multitenant:
  #   image: wernight/ngrok
  #   command: ngrok http multitenant-agent:${MULTITENANT_HTTP_PORT} --log stdout
  #   networks:
  #     - indy_demo
  # multitenant-agent:
  #   build:
  #     context: .
  #     dockerfile: agents/Dockerfile.ngrok
  #   environment:
  #     - NGROK_NAME=ngrok-multitenant
  #     - ADMIN_URL=http://multitenant-agent:${MULTITENANT_ADMIN_PORT}
  #     - AGENT_NAME=${MULTITENANT_AGENT_NAME}
  #     - ADMIN_PORT=${MULTITENANT_ADMIN_PORT}
  #     - HTTP_PORT=${MULTITENANT_HTTP_PORT}
  #     - ACAPY_WEBHOOK_URL=${MULTITENANT_WEBHOOK_URL}
  #     - AGENT_ENDPOINT=${MULTITENANT_AGENT_ENDPOINT}
  #     - WALLET_SEED=${MULTITENANT_WALLET_SEED}
  #     - WALLET_NAME=${MULTITENANT_WALLET_NAME}
  #     - WALLET_KEY=${MULTITENANT_WALLET_KEY}
  #     - WALLET_TYPE=${WALLET_TYPE}
  #     - ACAPY_ADMIN_INSECURE_MODE=${MULTITENANT_ADMIN_SECURE}
  #     - GENESIS_URL=${GENESIS_URL}
  #     - ACAPY_MULTITENANT=true
  #     - ACAPY_MULTITENANT_JWT_SECRET="password"
  #     - ACAPY_MULTITENANT_ADMIN=true
  #     - ACAPY_WALLET_STORAGE_TYPE=postgres_storage
  #     - ACAPY_WALLET_STORAGE_CONFIG={"url":"wallets-db:5432","wallet_scheme":"MultiWalletSingleTable"}
  #     - ACAPY_WALLET_STORAGE_CREDS={"account":"postgres","password":"dbpass","admin_account":"postgres","admin_password":"dbpass"}
  #   ports:
  #     - ${MULTITENANT_HTTP_PORT}:${MULTITENANT_HTTP_PORT}
  #     - ${MULTITENANT_ADMIN_PORT}:${MULTITENANT_ADMIN_PORT}
  #   depends_on:
  #     - wallets-db
  #   networks:
  #     - indy_demo

networks:
  indy_demo:
